# 站点信息
site_name: WALI_FrameWork  # 文档站点名称
site_description: A sample documentation site  # 文档站点描述
site_author: kk # 文档作者

# 导航栏
nav:
  - Home: index.md  # 首页
  - Getting Started:  # 入门指南
    - Installation: installation.md  # 安装指南
    - Quick Start: quick-start.md  # 快速入门
  - User Guide:  # 用户指南
    - Configuration: config.md  # 配置
    - Usage: usage.md  # 使用方法
  - API Reference:  # API 参考
    - Module A: api/module_a.md  # 模块 A
    - Module B: api/module_b.md  # 模块 B
  - About:
    - Overview: about/about.md
    - Team: about/team.md
  - signals_slots:
    - Overview: signals_slots/C语言模拟QT的信号与槽功能.md
# 主题配置
theme:
  name: readthedocs  # 使用 readthedocs 主题
  show_powered_by: false  # 隐藏 Powered by Read the Docs 标志

# 额外的 CSS 样式
extra_css:
  - css/custom.css  # 自定义 CSS 样式文件
