# 站点信息
site_name: My Documentation  # 文档站点名称
site_description: A sample documentation site  # 文档站点描述
site_author: Your Name  # 文档作者
site_url: https://your-docs-url.com  # 文档站点 URL

# 导航栏
nav:
  - Home: index.md  # 首页
  - Getting Started:  # 入门指南
    - Installation: installation.md  # 安装指南
    - Quick Start: quick-start.md  # 快速入门
  - User Guide:  # 用户指南
    - Configuration: config.md  # 配置
    - Usage: usage.md  # 使用方法
  - API Reference:  # API 参考
    - Module A: api/module_a.md  # 模块 A
    - Module B: api/module_b.md  # 模块 B
  - About:  # 关于
    - Overview: about.md  # 概述
    - Team: team.md  # 团队
  - Signals and Slots: signals_slots/C语言模拟QT的信号与槽功能.md  # 信号与槽功能

# 主题配置
theme:
  name: readthedocs  # 使用 readthedocs 主题
  logo: img/logo.png  # 站点 Logo
  favicon: img/favicon.ico  # 站点图标
  show_powered_by: false  # 隐藏 Powered by Read the Docs 标志

# 额外的 CSS 样式
extra_css:
  - css/custom.css  # 自定义 CSS 样式文件
