# 站点信息
site_name: WALI_FrameWork  # 文档站点名称
site_description: A sample documentation site  # 文档站点描述
site_author: kk # 文档作者

# 导航栏
nav:
  - Home: index.md  # 首页
  - Getting Started:  # 入门指南
    - 快速上手: quick-start.md  # 快速入门
  - 用户指南:  # 用户指南
    - 配置: config.md  # 配置
    - 使用方法: usage.md  # 使用方法
  - 重点基础知识: 
    - 变参函数和可变参数宏: config.md  # 配置
    - 线程安全和函数可重入: usage.md  # 使用方法   
    - 异步与同步:   
    - 状态机: 
  - 信号槽: signals_slots/C语言模拟QT的信号与槽功能.md
  - 发布订阅:
  - msgmap:
  - shell:
  - About:
    - Overview: about/about.md
    - Team: about/team.md


# 主题配置
theme:
  name: readthedocs  # 使用 readthedocs 主题
  show_powered_by: false  # 隐藏 Powered by Read the Docs 标志

# 额外的 CSS 样式
extra_css:
  - css/custom.css  # 自定义 CSS 样式文件
